jwt:
  secret: mysuperlongjwtsecretkeywithatleast32characters!!

server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/todo_app_db?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456789

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shuttle.proxy.rlwy.net:55813/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: cuBxZyELlumrqkCRXElnZXXsxAQEIMtU

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true
